name: CSCI 1270 - Database Management Systems
output: build
static_src: static
static_dest: static

partials:
  header: views/partials/header.tmpl
  post-header: views/partials/post-header.tmpl
  footer: views/partials/footer.tmpl

pages:
  - title: Home
    path: /
    template: views/index.tmpl
    data:
      assignment: src-snipped/data/assignment.yaml
      gearup: src-snipped/data/gearup.yaml
      faq: src-snipped/data/faq.yaml
      lecture: src-snipped/data/lecture.yaml
      seminar: src-snipped/data/seminar.yaml
      staff: src-snipped/data/staff.yaml

collections:
  - title: Project
    path: /project
    template: views/handout.tmpl
    posts: src-snipped/docs/project
  - title: Homework
    path: /homework
    template: views/handout.tmpl
    posts: src-snipped/docs/homework
  - title: Misc
    path: /misc
    template: views/misc.tmpl
    posts: src-snipped/docs/misc
